### ISSUE TITLE
change reading of header

### ISSUE THREAD

**Issue by konne** [senseexcel/ser-con-aai#111]
In Code line: https://github.com/senseexcel/ser-con-aai/blob/5d930ed3b304f36d24f5acaa3f93eee61c75ec0c/src/SerEvaluator.cs#L163 you use this complex code to reade the functionRequest header. Just use the same code like Line 170 and replace the CommenRequestHeader with FunctionRequestHeader. This is already solve nicely in the qlik-sse API Helpers.

**Comment by mossbeard** [comment]
Done
