### ISSUE TITLE
[Doc] Use the connector with one App

### ISSUE THREAD

**Issue by mossbeard** [senseexcel/ser-con-aai#23]
- separate Propery in the serapi general block - ConnectionRepeat
- Check if qlik session is available

**Comment by mossbeard** [comment]
Kein reguärer Weg!!!
Erst schließen wenn in Doku so dokumentiert.

**Comment by AlexanderGoerlich** [comment]
please close: https://github.com/senseexcel/senseexcel-reporting/blob/master/in-app-mode.md

**Comment by mossbeard** [comment]
Done
