### ISSUE TITLE
[Doc] Note in documentation - hjson property can not be empty.

### ISSUE THREAD

**Issue by mossbeard** [senseexcel/ser-con-aai#33]

**Comment by AlexanderGoerlich** [comment]
@harrislance pleaet set this as note to the docu!

**Comment by harrislance** [comment]
Welcome back. At a partner Qlik Sense world tour meeting in Jacksonville today. Back In the office on Thursday.


Sent From My I Phone With Regards,

Lance
S. Lance Harris
Managing Director
Sense Excel Reporting
Master Sales Agent
Tel +1 703 625 7738
Email: lharris@strategypoint.com
Email: lance@senseexcel.com
Web: www.senseexcel.com
________________________________

**Comment by AlexanderGoerlich** [comment]
do not set empty parameters in hjson config! Because in humanJSON can´t interpret this correctly. 

```
{
value: 
}

**Comment by AlexanderGoerlich** [comment]
please close: https://github.com/senseexcel/senseexcel-reporting/blob/master/scripting-notes.md

**Comment by mossbeard** [comment]
Done
