### ISSUE TITLE
invalid certificates / invalid for ip / name

### ISSUE THREAD

**Issue by konne** [senseexcel/ser-con-aai#6]
add 2 extra options:

1. sslVerify:off -> no verification, all ssl certificates are accepted
2. sslValidThumbprints: [
    { url: "*", thumbprint: "78 67 23 ,..." -> * means all URLS},
    { url: "10.1.17.2", thumbprint: "78 67 23 ,..." -> means that thumbprint for that url
    ]

**Comment by konne** [comment]
@mossbeard please change the url to correct URIs like:

uri:"https://10.1.17.2" or with wildcards "https://+" see ref https://stackoverflow.com/questions/7007929/what-does-a-plus-sign-mean-in-a-http-url-http-80

**Comment by mossbeard** [comment]
@konne Is resolve with emtpy url property
