### ISSUE TITLE
Fix 'Using static directives must be placed after using namespace directives.' issue in src\SerEvaluator.cs

### ISSUE THREAD

**Issue by konne** [senseexcel/ser-con-aai#79]
[CodeFactor](https://www.codefactor.io/repository/github/senseexcel/ser-con-aai/overview/development) found an issue: Using static directives must be placed after using namespace directives.

It's currently on:
[src\SerEvaluator.cs:35
](https://www.codefactor.io/repository/github/senseexcel/ser-con-aai/source/development/src/SerEvaluator.cs#L35)Commit 8ec482700a7a4a882d9bf2142508515cbc66e47e

**Comment by mossbeard** [comment]
Done
